### ISSUE TITLE
[Feature] Fixed sequences of blocks for better game design

### ISSUE THREAD

**Issue by Bogden** [BentoBoxWorld/AOneBlock#167]
From a game design perspective, the beginning of the game is a bit flawed in that players can generate blocks that they have not yet been given the resources to mine. An early sequence of cobblestone, for instance, before the player has gotten 3 logs. An iron ore before the player has gotten three stone, diamond before iron, etc.

For reference, this is how the original begins:
```
#
# 		Data pack by IJAMinecraft
# 		@ ijaminecraft.com
# 		@ youtube.com/user/IJAMinecraft
#

execute as @s[scores={ija-a4-counter=1}] at @s align xz positioned ~0.5 ~ ~0.5 run fill ~ ~ ~ ~ ~ ~ minecraft:grass_block replace minecraft:barrier

execute as @s[scores={ija-a4-counter=2}] at @s align xz positioned ~0.5 ~ ~0.5 run fill ~ ~ ~ ~ ~ ~ minecraft:grass_block replace minecraft:barrier

execute as @s[scores={ija-a4-counter=3}] at @s align xz positioned ~0.5 ~ ~0.5 run fill ~ ~ ~ ~ ~ ~ minecraft:grass_block replace minecraft:barrier

execute as @s[scores={ija-a4-counter=4}] at @s align xz positioned ~0.5 ~ ~0.5 run fill ~ ~ ~ ~ ~ ~ minecraft:oak_log replace minecraft:barrier

execute as @s[scores={ija-a4-counter=5}] at @s align xz positioned ~0.5 ~ ~0.5 run fill ~ ~ ~ ~ ~ ~ minecraft:oak_log replace minecraft:barrier

execute as @s[scores={ija-a4-counter=6}] at @s align xz positioned ~0.5 ~ ~0.5 run fill ~ ~ ~ ~ ~ ~ minecraft:chest[facing=east]{"LootTable":"ija-one-block:00"} replace minecraft:barrier

```

In terms of AOneBlock, maybe something like this could work:
```yml
'0':
  name: Plains
  fixedBlocks:
    0: GRASS_BLOCK
    1: GRASS_BLOCK
    2: GRASS_BLOCK
    3: OAK_LOG
    4: OAK_LOG
    5: OAK_LOG
    # etc, etc
    700: CHEST_WITH_WATER_BUCKET
  biome: PLAINS
  blocks:
    PODZOL: 40
    MYCELIUM: 40
    BIRCH_LEAVES: 100
    IRON_ORE: 300
    CHEST: 200
    BEE_NEST: 20
    OAK_LOG: 2000
    DIRT: 1000
    ANDESITE: 100
    INFESTED_STONE: 40
    DARK_OAK_LOG: 300
    OAK_LEAVES: 1000
    BROWN_MUSHROOM_BLOCK: 100
    DIORITE: 100
    COAL_ORE: 700
    GRAVEL: 100
    DIAMOND_ORE: 30
    GOLD_ORE: 30
    GRASS_BLOCK: 2000
    DARK_OAK_LEAVES: 100
    BIRCH_LOG: 500
    COBBLESTONE: 800
    SAND: 200
    GRANITE: 400
    COARSE_DIRT: 100
    STONE: 800
    CLAY: 40
    EMERALD_ORE: 10
    GRASS_PATH: 100
  mobs:
    COW: 150
    SPIDER: 75
    SHEEP: 75
    PIG: 150
    VILLAGER: 15
    CHICKEN: 200
```
