### ISSUE TITLE
Phase Holograms

### ISSUE THREAD

**Issue by iRobSch** [BentoBoxWorld/AOneBlock#340]
### Expected behavior

1. The holograms are supposed to display the appropriate colour that is in the phase's name;
2. The holograms are supposed to be disabled when their configuration option is set to `false`.

### Observed/Actual behavior

https://media.discordapp.net/attachments/310623455462686720/1154306762254598234/image.png?width=1440&height=671

Holograms cannot be killed as an entity - furthermore, you can see the colours do not work. It was reported in the Discord that holograms apparently do not yet have colour support because of an issue.

Furthermore, here's a part of the config:
```
world:
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: OneBlock
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end (e.g. oneblock_world, oneblock_world_nether, oneblock_world_end)
  world-name: oneblock
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: HARD
  # Display holograms
  holograms: false
```

### Steps/models to reproduce

Disable holograms in config for one issue, advance to a new phase for the other issue.

### BentoBox version

[02:51:27 INFO]: Running Invalid (PUFFERFISH) 1.20.1.
[02:51:27 INFO]: BentoBox version: 1.24.1
[02:51:27 INFO]: Database: JSON
[02:51:27 INFO]: Loaded Game Worlds:
[02:51:27 INFO]: oneblock (OneBlock): Overworld, Nether*, The End*
[02:51:27 INFO]: Loaded Addons:
[02:51:27 INFO]: AOneBlock 1.14.2 (ENABLED)
