### ISSUE TITLE
bug with custom alphabet in placeholders

### ISSUE THREAD

**Issue by Mithranduil** [BentoBoxWorld/AOneBlock#366]
### Expected behavior

normally shown the ob phases name

### Observed/Actual behavior

using "name: ᴡɪᴇsᴇɴ" in config, but it only shows ???????

### Steps/models to reproduce

add an config phase with "'0':
  name: ᴡɪᴇsᴇɴ" and join server 

### BentoBox version

2.0.0- SnapShot - b2496
Paper 1.20.1

**Comment by Mithranduil** [comment]
other placeholders or textes in scoreboards with that letter format works fine, only the phases of oneblock are stucked

**Comment by tastybento** [comment]
Hmm, I can't seem to replicate. I'm using PAPI 2.11.2:

```
> papi parse BoxManager %aoneblock_my_island_phase%
[14:32:59 INFO]: ᴡɪᴇsᴇɴ
```
<img width="680" alt="Screenshot 2024-01-26 at 2 34 49 PM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/118e9fb1-bc35-4df2-b850-8f5597324327">

<img width="448" alt="Screenshot 2024-01-26 at 2 33 32 PM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/a5c1e033-29ea-4ab4-9c32-681c9f3a3270">
<img width="847" alt="Screenshot 2024-01-26 at 2 37 53 PM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/17eb48f8-670c-435e-a645-3592d6fc4669">

**Comment by tastybento** [comment]
Is there some way to make this happen that I'm missing?

**Comment by Mithranduil** [comment]
can you add this placeholder now in the hologram and then restart server and connect new?

cause thats when its not showing right.
after i update the hologram (likely break an block and its update the hologram) the missing letters appears directly and it shows the correct oneblock phase

**Comment by tastybento** [comment]
How do you add the placeholder in the hologram?

**Comment by tastybento** [comment]
I tried with Animated Scoreboard and it seems to work...
<img width="850" alt="Screenshot 2024-01-27 at 5 18 35 PM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/46dfae29-df88-4f97-9cea-60f27e71efb2">

I just set the default admin scoreboard entry like this:

```
    line-2:
      text:
      - "&a&lWelcome %aoneblock_my_island_phase%"
      - "&b&lWelcome %aoneblock_my_island_phase%"
      - "&c&lWelcome %aoneblock_my_island_phase%"   
      random: false
      interval: 5
      score: 98
```

I'm not sure why you are seeing ?????'s but it may be an OS thing?
