### ISSUE TITLE
Phase loot chests

### ISSUE THREAD

**Issue by Adwhitney** [BentoBoxWorld/AOneBlock#381]
### Expected behavior

I expect that if I create a new phase and put loot crates in it that they will spawn in OB

### Observed/Actual behavior

I created a new phase and then put loot crates in it, but in OB the loot chest didn't spawn at all

### Steps/models to reproduce

The console doesn't throw any errors.

### BentoBox version

 Running Invalid (PUFFERFISH) 1.20.2.
 (git-Pufferfish-35 (MC: 1.20.2))
BentoBox version: 2.1.0
 Database: JSON
Loaded Game Worlds:
 oneblock_world (OneBlock): Overworld, Nether*, The End*
Loaded Addons:
 AOneBlock 1.15.0 (ENABLED)
Challenges 1.2.0 (ENABLED)
 Greenhouses 1.7.5 (ENABLED)
 Level 2.12.0 (ENABLED)
 Warps 1.14.0 (ENABLED)

### Plugin list

BentoBox, ASkyBlock, Challanges, Greenhouses, Level, Warps

### Other

Every time I created a new phase it was fine, then I used /oba setchest <phase> COMMON and everything was added to the configuration, but the loot boxes didn't show up in OB.

**Comment by tastybento** [comment]
You will need to share the OB phase and chest file. I recommend you zip them up and drag and drop them here. They are in the BentoBox/addons/AOneBlock/phases folder.

**Comment by tastybento** [comment]
In the blocks section of the phase file, you need to include some chests in there, otherwise they will not spawn. When they do spawn, then the game will select which one to spawn from the other file. So for example, make your phase file:

```
'26000':
  name: Hory
  firstBlock: MOSSY_COBBLESTONE
  biome: STONY_PEAKS
  fixedBlocks: {}
  blocks:
    CHEST: 200
    EMERALD_ORE: 30
    COBBLESTONE: 399
    INFESTED_STONE: 150
    STONE: 500
    SMOOTH_STONE: 250
    INFESTED_COBBLESTONE: 150
    COAL_ORE: 60
    MOSSY_COBBLESTONE: 200
    IRON_ORE: 80
    CALCITE: 99
  mobs:
    WOLF: 40
    WITCH: 30
    GOAT: 50
    SKELETON: 60
  holograms: {}
  start-commands: []
  end-commands: []
```
