### ISSUE TITLE
Placeholder regarding the progress: v1.19.0-SNAPSHOT

### ISSUE THREAD

**Issue by tooobiiii** [BentoBoxWorld/AOneBlock#426]
### Expected behavior

%aoneblock_visited_island_blocks_to_next_phase% should accurately display the blocks needed to break to achieve the next phase

### Observed/Actual behavior

%aoneblock_visited_island_blocks_to_next_phase% is always one off / too far
https://medal.tv/games/minecraft/clips/kb58ueeEVTj4d7n07?invite=cr-MSx0eXUsMTkwMTkzNTA

### Steps/models to reproduce

As in the video

### BentoBox version

![Image](https://github.com/user-attachments/assets/41f25b8b-a16e-47b6-99ca-371809a884cf)

![Image](https://github.com/user-attachments/assets/aa003043-5565-4d1a-a007-077405312280)

### Plugin list

![Image](https://github.com/user-attachments/assets/d3c40e58-5d0e-4684-a3eb-8477ec4874a3)

**Comment by tooobiiii** [comment]
also tabcomplete doesnt work on bossbar cmd

**Comment by tooobiiii** [comment]
And please let us customize the bossbar ourselves. 
So we can e.g edit it so it also displays the phase and percentage

**Comment by tooobiiii** [comment]
Just giving some input regarding this being a snapshot

**Comment by tastybento** [comment]
In regards to `%aoneblock_visited_island_blocks_to_next_phase%` - it looks like it is actually correct. The value of [done] in the boss bar seems to be one off. I'll see how to fix it.

> also tabcomplete doesnt work on bossbar cmd

The player boss bar command is just a toggle. There are no parameters. Or am I misunderstanding?

> And please let us customize the bossbar ourselves.

The bar can be visually customized here:
```
aoneblock:
  bossbar:
    title: "Blocks remaining"
    # status: "&a Phase blocks &b [total]. Blocks left: [todo]"
    status: "&a Phase blocks &b [done] &d / &b [total]"
    # RED, WHITE, PINK, BLUE, GREEN, YELLOW, or PURPLE
    color: RED
    # SOLID, SEGMENTED_6,  SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
    style: SOLID
    not-active: "&c Boss Bar is not active for this island"
```

> So we can e.g edit it so it also displays the phase and percentage

Okay, you want to be able to add [phase-name] and [percent-done] as placeholders?
